### ISSUE TITLE
Off-topic: Kawai CN37

### ISSUE THREAD

**Issue by lwasyl** [zommuter/numintropy#6]
Hello,

Sorry for unsolicited contact -- I even feel wierd writing to you, especially on Github. I have found your profile on music.stackexchange, where you claim to have bought Kawai CN37 digital piano, and that you couldn't recommend it enough, and I decided to search for a way to contact you to ask you a question:

I myself own this piano as well, but mine has developed a clicky sound when lifting the keys -- slight, high-pitched 'click' sound, as if a small plastic element hitting another plastic element. I've obviously filed a warranty claim, but _my dealer responded, that Kawai claims this sound is normal_. It only appeared after few weeks of use, so I wanted to ask you -- as you would have had this piano for some time now -- does your piano also have this slight clicky sound when depressing the keys, particularly in the middle (most often used) part of the keyboard? It's the loudest if you press whole chord in the middle of the keyboard with the piano off, and then lift all fingers at once.

According to my dealer, it's some layef of grease below the keys that got thin (because of the usage), and now depressing the keys causes it to split, causing a slight 'plop' if you will.

I'm looking for opinions of other CN37 users, since I strongly believe this isn't expected, and my piano is faulty. With its price, I put a lot of effort into investigating this, so I'm writing to you as well.

I hope you don't mind me contacting you, and I'd be immensely grateful for any information regarding keys sound on your CN37. I hope I'm not mistaken, and found the proper Tobias K. :) 

I'll happily exchange emails if you wish, you can reach me on twitter: @_wasyl

Best Regards,
Lucas

**Comment by zommuter** [comment]
Creative way to reach out 😁
[Said comment](https://music.stackexchange.com/questions/61733/what-should-i-take-into-consideration-when-buying-my-first-digital-piano/61736#comment94425_61733) is still valid, I didn't have any trouble so far, though admittedly I don't play too regularly. http://music.stackexchange.com is a better choice for this question though, since there you'll get a bigger statistical sample size and might even get feedback from other pianos' users with similar issues. I hope you'll get this fixed, it doesn't sound natural to me...

So anyway, for future questions by the world in general (as if...) I set up https://github.com/zommuter/ama
